on: [push]

jobs:
  hidden_directory_job:
    runs-on: ubuntu-latest
    name: A job to hidden directory
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Hello world action step
        uses: ./ 
        id: hidden
        with:
          password: 'Mona the Octocat'
      - name: Get the output time
        run: echo "The sharekey is ${{ steps.hidden.outputs.sharekey }}"