on: [push]

jobs:
  hidden_directory_job:
    runs-on: ubuntu-latest
    name: A job to hidden directory
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Hidden directory action step
        uses: ./ 
        id: hidden
        with:
          password: 'Mona the Octocat'
      - name: Show info
        run: |
          echo "sharekey ${{ steps.hidden.outputs.sharekey }}"
          echo "directory ${{ steps.hidden.outputs.directory }}"
      - name: Show file
        run: |
          pwd
          ls -la ./client/
          cat ./client/sharekey.js
